name: distill_ds
channels:
  - pytorch
  - nvidia
  # - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.7 # Use 'cudatoolkit' for the CUDA dependency instead of 'pytorch-cuda'
  - pip
  - pip:
    - transformers<=4.45.2
    - setuptools==69.5.1
    - pydantic==1.10.13
    - datasets>=1.8.0
    - sentencepiece!=0.1.92
    - protobuf==3.20.*
    - wandb
    - accelerate>=0.12.0
    - chardet
    - rouge-score
    - nltk
    - py7zr
    - evaluate
    - git+https://github.com/google-research/bleurt.git
    - typer[all]
    - omegaconf
    - InstructorEmbedding
    - openai
    - adapters
    - tf-keras
    - huggingface_hub
    - deepspeed==0.12.0
    # - langchain
    - tiktoken
    # - thefuzz[speedup]
    # - git+https://github.com/huggingface/peft.git # Uncomment if needed
# conda env create -f environment.yml
# conda env update -f environment.yml